### ISSUE TITLE
 学習データの詳細

### ISSUE THREAD

**Issue by akiFQC** [ujiuji1259/shinra-attribute-extraction#3]
学習データは[ダウンロードページ](http://shinra-project.info/shinra2020jp/data_download)の「森羅2020-JPタスクの学習・ターゲットデータ（トークナイズ済み, Mecab(IPA辞書)&BPE使用, 東北大BERT対応)」という認識で合っていますでしょうか？

**Comment by ujiuji1259** [comment]
はい、そのデータを使用しています。
READMEに明示するようにします。ありがとうございます。

**Comment by akiFQC** [comment]
ありがとうございます。
